// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/servicios": {
    params: {};
  };
  "/sobre-nosotros": {
    params: {};
  };
  "/contactanos": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/servicios" | "/sobre-nosotros" | "/contactanos";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/servicios.tsx": {
    id: "routes/servicios";
    page: "/servicios";
  };
  "routes/sobre-nosotros.tsx": {
    id: "routes/sobre-nosotros";
    page: "/sobre-nosotros";
  };
  "routes/contactanos.tsx": {
    id: "routes/contactanos";
    page: "/contactanos";
  };
};